# Generated by Django 4.2.3 on 2023-07-27 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_someothermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someothermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
