# Generated by Django 4.2.3 on 2023-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_customuser_phone_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('therapy_type', models.CharField(max_length=100)),
                ('cv', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='psychologists/')),
            ],
        ),
    ]
