# Generated by Django 4.2.3 on 2023-08-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
